version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/sensor_hub"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/sensor_hub/ui/sensor_hub_ui"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/temperature_sensor"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/sensor_hub/docker_tests"
    schedule:
      interval: "weekly"
