services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sensor_database
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 15s
      timeout: 5s
      retries: 10
  flyway:
    image: flyway/flyway:latest
    command: -url='jdbc:mysql://mysql:3306/sensor_database?allowPublicKeyRetrieval=true&useSSL=false' -user=root -password=password -locations=filesystem:/flyway/sql -baselineOnMigrate=true migrate
    volumes:
      - ../db/changesets:/flyway/sql
    depends_on:
      mysql:
        condition: service_healthy
  sensor-hub:
    build:
      context: ..
      dockerfile: docker_tests/sensor-hub.dockerfile
    depends_on:
      flyway:
        condition: service_completed_successfully
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "2345:2345"
    volumes:
      - ../:/app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: password
  sensor-hub-ui:
    build:
      context: ../ui/sensor_hub_ui
      dockerfile: sensor-hub-ui-test.dockerfile
      args:
        VITE_API_BASE: "http://localhost:8080"
        VITE_WEBSOCKET_BASE: "ws://localhost:8080"
    ports:
      - "3000:5173"
    volumes:
      - ../ui/sensor_hub_ui:/app
      - /app/node_modules
    depends_on:
      - sensor-hub
  mock-sensor-downstairs:
    build:
      context: .
      dockerfile: mock-sensor.dockerfile
    ports:
      - "5001:5000"
  mock-sensor-upstairs:
    build:
      context: .
      dockerfile: mock-sensor.dockerfile
    ports:
      - "5002:5000"
volumes:
  mysql-data:
